name = "jeongwoo-in-shell"
compatibility_date = "2024-12-05"
pages_build_output_dir = "dist"

# R2 Bucket Binding for sitemap
[[r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "blog"
preview_bucket_name = "blog"
